### ISSUE TITLE
您好，我想请问下直线的定义；

### ISSUE THREAD

**Issue by yuanbianxiyang** [lgf133214/backup_of_homework#1]
一般定义直线考两点，或者y = ax + b，来定义，您代码中的参数有a ， b， c是什么意思呢？ 是 ax + by = c ,吗

**Comment by lgf133214** [comment]
emm...我写清楚了吧应该，ax+by+c=0，时间有点久了😂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lgf133214/backup_of_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午2:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lgf133214/backup_of_homework] 您好，我想请问下直线的定义； (Issue #1)





 
一般定义直线考两点，或者y = ax + b，来定义，您代码中的参数有a ， b， c是什么意思呢？ 是 ax + by = c ,吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuanbianxiyang** [comment]
好的好的，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lgf133214/backup_of_homework] 您好，我想请问下直线的定义； (Issue #1)





 emm...我写清楚了吧应该，ax+by+c=0，时间有点久了😂 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "lgf133214/backup_of_homework"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月16日(星期二) 下午2:35 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[lgf133214/backup_of_homework] 您好，我想请问下直线的定义； (Issue #1) 
 
 
 
 
 
   
 一般定义直线考两点，或者y = ax + b，来定义，您代码中的参数有a ， b， c是什么意思呢？ 是 ax + by = c ,吗 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
